---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tuga9652/public_html
    - /bin/rsync -av --exclude=.git --exclude=node_modules --exclude=storage/framework/views . $DEPLOYPATH
    - echo "Deployment completed"
